### ISSUE TITLE
[REQUEST] Big Beans

### ISSUE THREAD

**Issue by DayBr3ak** [SpaceGameDev568/RemoveAllAnnoyances#1]
Could you please include the Big bloated beans on 4 legs in your annoyance list?

Cheers

**Comment by SpaceGameDev568** [comment]
Hi, I can certainly do that for you! Expect this feature to arrive in the next update.

**Comment by SpaceGameDev568** [comment]
Done. https://ficsit.app/mod/FGnDVTV2ygmANY/version/DA9vr1QYBMXwpW
