### ISSUE TITLE
Gas Plants Option missing and chat message.

### ISSUE THREAD

**Issue by mindcloud69** [SpaceGameDev568/RemoveAllAnnoyances#4]
### Operating System

Windows 10/11

### Environment

Single Player

### Game Version

Stable

### SML Version

3.8.0

### Mod Version

2.0.2

### Describe the bug

Option to remove gas plants is not there. Also can you add an option to remove the annoying chat message when a script is not enabled.

### Expected Behavior

Option to remove Gas Plants and chat message.

### Attachments

![image](https://github.com/user-attachments/assets/12010a86-c5e0-4e21-980c-a1d25207dc21)

**Comment by SpaceGameDev568** [comment]
I assume you're referring to the Spore Flowers, which are covered under the **Gas Pillars** category already. If you would prefer it to be a separate option, please let me know.
As for the chat message, it should only appear once. If you are seeing it and don't want to enable any scripts, then what's even the point of using the mod?

**Comment by mindcloud69** [comment]
I would prefer it was a separate option. Do you think you could also add one for the chat message? 

Thank you for your work and time on the mod!

**Comment by SpaceGameDev568** [comment]
Alright, I've added both in RAA v2.0.3. Enjoy!

**Comment by mindcloud69** [comment]
Thank you!
